### ISSUE TITLE
相机的参数

### ISSUE THREAD

**Issue by wenyuanqin** [RoboMaster/IntelligentUAVChampionshipSimulator#24]
相机的焦距和基线能否提供

**Comment by ShihaoLuo** [comment]
规则手册中有提供。

**Comment by qwy826673487** [comment]
非常感谢，基线有提供，但是没有看到焦距

> 规则手册中有提供。

**Comment by wenyuanqin** [comment]
> 规则手册中有提供。

感谢，手册中确实有，麻烦问一下，控制命令中的角度是弧度还是角度

**Comment by wenyuanqin** [comment]
坐标系可以发布一下吗

**Comment by ShihaoLuo** [comment]
FRD机体系，弧度制。

**Comment by CodeJackcl** [comment]
> > 规则手册中有提供。
> 
> 感谢，手册中确实有，麻烦问一下，控制命令中的角度是弧度还是角度

你好，请问相机的焦距在手册中是多少呢？只看到了基线，

**Comment by wenyuanqin** [comment]
> > > 规则手册中有提供。
> > 
> > 
> > 感谢，手册中确实有，麻烦问一下，控制命令中的角度是弧度还是角度
> 
> 你好，请问相机的焦距在手册中是多少呢？只看到了基线，

确实只有基线，但是双目测距有基线就够了

**Comment by CodeJackcl** [comment]
> > > > 规则手册中有提供。
> > > 
> > > 
> > > 感谢，手册中确实有，麻烦问一下，控制命令中的角度是弧度还是角度
> > 
> > 
> > 你好，请问相机的焦距在手册中是多少呢？只看到了基线，
> 
> 确实只有基线，但是双目测距有基线就够了
> > 从视差图转换到深度图需要焦距阿

**Comment by ZJW-HUST** [comment]
请问相机到body的外参是要自己测吗

**Comment by ShihaoLuo** [comment]
> > > 规则手册中有提供。
> > 
> > 
> > 感谢，手册中确实有，麻烦问一下，控制命令中的角度是弧度还是角度
> 
> 你好，请问相机的焦距在手册中是多少呢？只看到了基线，

规则手册中已经有了 FOV和图像大小，这个参数与焦距是等价的。也可以自己用标定板测算。

**Comment by ShihaoLuo** [comment]
> 请问相机到body的外参是要自己测吗

规则手册中有提供， 模拟器中的 settings.json也有。建议通过标定板自己测算一遍。

**Comment by ZJW-HUST** [comment]
> > 请问相机到body的外参是要自己测吗
> 
> 规则手册中有提供， 模拟器中的 settings.json也有。建议通过标定板自己测算一遍。

好的，谢谢了
