### ISSUE TITLE
话题

### ISSUE THREAD

**Issue by wenyuanqin** [RoboMaster/IntelligentUAVChampionshipSimulator#25]
airsim_node/drone_1/pose_cmd_body_frame  发布偏航角
airsim_node/drone_1/angle_rate_throttle_frame 发布偏航角速率 
这个控制输入是弧度还是角度

**Comment by wenyuanqin** [comment]
坐标系定义可以给一下吗

**Comment by ShihaoLuo** [comment]
均为FRD机体系。
