### ISSUE TITLE
imu话题数据异常

### ISSUE THREAD

**Issue by dongdong-cai** [RoboMaster/IntelligentUAVChampionshipSimulator#27]
/airsim_node/drone_1/imu/imu话题的线加速度，其X和Y轴一直维持在0左右，我用键盘控制从图像可以明显看到无人机姿态的一个倾斜，但此时imu话题的XY轴加速度依旧维持在0附近，是正常现象嘛？

**Comment by ShihaoLuo** [comment]
正常现象
