### ISSUE TITLE
这个docker容器有什么用，我运行之后报错

### ISSUE THREAD

**Issue by FangLian9101** [RoboMaster/IntelligentUAVChampionshipSimulator#28]
这个容器命令./run_docker_simulator.sh 123是干什么用的，然后我运行之后报错
docker: Error response from daemon: Requested CPUs are not available - requested 0-9, available: 0-7.
See 'docker run --help'.
有人知道怎么解决吗

**Comment by ShihaoLuo** [comment]
这个报错说明你的cpu仅有8个核可以用，可以把0-9改为0-7试试。
