### ISSUE TITLE
imu线加速度计数据问题

### ISSUE THREAD

**Issue by Ding-Guo** [RoboMaster/IntelligentUAVChampionshipSimulator#29]
如图所示，可从其图片的倾斜以及四元数明显看到无人机斜着一定角度，可Imu数据中y轴却没有数据。这是否说明仿真中的imu线加速度数据是错误的

![2023-09-21 21-30-40 的屏幕截图](https://github.com/RoboMaster/IntelligentUAVChampionshipSimulator/assets/50550885/9e9eab30-ef76-4acb-900d-5474c8a53760)

**Comment by ShihaoLuo** [comment]
当无人机为静止状态时，加速度就已经是0了。经过测试，模拟器imu没有问题。
