### ISSUE TITLE
打开Simulator很卡、黑屏怎么办

### ISSUE THREAD

**Issue by 186big** [RoboMaster/IntelligentUAVChampionshipSimulator#30]

**Comment by 186big** [comment]
![1695606632000](https://github.com/RoboMaster/IntelligentUAVChampionshipSimulator/assets/97373109/aaa115f7-066a-4e0d-8aa8-2ae861024234)

**Comment by ShihaoLuo** [comment]
你用的是什么显卡？

**Comment by 186big** [comment]
> 你用的是什么显卡？

3060独显，感觉没有用到显卡，怎么让其使用显卡呢

**Comment by ShihaoLuo** [comment]
你可以打开模拟器后使用 nvidia-smi 查看显卡占用，一般占用为40说明模拟器再使用nvidia显卡。如果没有则说明显卡没启动，可能使用了核显。 此时可以使用  sudo prime-select nvidia 切换全局默认显卡再尝试开启模拟器。

**Comment by 186big** [comment]
> Collabora
nvidia-smi可以显示显卡占用，也显示3060显卡，并没有占用很多，说明没用到显卡，当使用sudo prime-select nvidia时候报错
Error: no integrated GPU detected.我并没有核显，怎么选择不到独显呢

**Comment by 186big** [comment]
> 你可以打开模拟器后使用 nvidia-smi 查看显卡占用，一般占用为40说明模拟器再使用nvidia显卡。如果没有则说明显卡没启动，可能使用了核显。 此时可以使用 sudo prime-select nvidia 切换全局默认显卡再尝试开启模拟器。

我使用了nvidia-smi命令显示显卡占用，模拟器并没有使用nvidia显卡，主机也没有核显，估计用cpu在跑，运行 sudo prime-select nvidia 会报错没有核显Error: no integrated GPU detected.

**Comment by ShihaoLuo** [comment]
重新安装显卡驱动试一下？

**Comment by Immortalqx** [comment]
> ![1695606632000](https://user-images.githubusercontent.com/97373109/270208993-aaa115f7-066a-4e0d-8aa8-2ae861024234.jpg)

您好！请问仿真平台的深度图（截图左下角）是如何获取的？
