### ISSUE TITLE
simulator 能否兼容ros melodic?

### ISSUE THREAD

**Issue by Bug0writer** [RoboMaster/IntelligentUAVChampionshipSimulator#31]
我尝试在安装了ros melodic 的电脑上运行命令：
~/IntelligentUAVChampionshipSimulator/Build/LinuxNoEditor$  ./RMUA.sh -seed=123
但是出现这个报错：
~/IntelligentUAVChampionshipSimulator/Build/LinuxNoEditor/RMUA/Binaries/Linux/RMUA-Linux-Shipping: error while loading shared libraries: libavcodec.so.58: cannot open shared object file: No such file or directory

**Comment by ShihaoLuo** [comment]
缺失了相关库 使用 sudo apt install ffmpeg 指令安装。

**Comment by initialjj** [comment]
Ubuntu18无法运行，安装ffmpeg后仍未解决，报错如下
![screenshot](https://raw.githubusercontent.com/Jeffrey0418/MarkdownPhotos/main/res/screenshot.png)

**Comment by ShihaoLuo** [comment]
18.04的ffmpeg默認裝的不是 .58版本。 可以嘗試把創建一個 libavcodec.so 的軟連接 指向 libavcodec.so.58。 或者嘗試安裝 sudo apt install libavcodec58 （可能18.04的軟件庫沒有）。 最簡單的方式是 用20.04的系統裝 ffmpeg.
