### ISSUE TITLE
为什么为单独输入一个pose_cmd_body_frame测试时 给airism 里面的无人机一直没有反映呢 

### ISSUE THREAD

**Issue by cwc2023** [RoboMaster/IntelligentUAVChampionshipSimulator#32]
代码如下：
#include <ros/ros.h>
#include <quadrotor_msgs/PositionCommand.h>
#include "airsim_ros/PoseCmd.h"

int main(int argc, char** argv) {
    ros::init(argc, argv, "pos_cmd_test");
    ros::NodeHandle nh;

  
    ros::Publisher pos_cmd_pub = nh.advertise<airsim_ros::PoseCmd>("/airsim_node/drone_1/pose_cmd_body_frame", 1);

   
    airsim_ros::PoseCmd posecmd;
    

 

    // 使用publisher发布速度指令需要定义 posecmd , 并赋予相应的值后，将他publish（）出去
    posecmd.roll = 0; //x方向姿态(rad)
    posecmd.pitch = 0;//y方向姿态(rad)
    posecmd.yaw = 3;//z方向姿态(rad)
    posecmd.throttle = 0.5;//油门， （0.0-1.0）

    ros::Rate rate(10);  // 设置发布频率为10Hz

    while (ros::ok()) {
        pos_cmd_pub.publish(posecmd);
        std::cout<< "-------------" <<posecmd.throttle << std::endl;
        rate.sleep();
    }
    return 0;
}

**Comment by cwc2023** [comment]
![图片](https://github.com/RoboMaster/IntelligentUAVChampionshipSimulator/assets/136964016/fad78d89-730e-4e13-976e-88dcaef0755e)
当我油门设置为1的时候，就可以起飞

**Comment by ShihaoLuo** [comment]
因爲0.6以上的油門無人機才飛得起來
