### ISSUE TITLE
使用rostopic echo /airsim_node/drone1/debug/circle_poses_gt和rostopic echo /airsim_node/drone1/circle_poses报错

### ISSUE THREAD

**Issue by 1054427212** [RoboMaster/IntelligentUAVChampionshipSimulator#33]
在之前版本的simulator中能正常运行，在新的版本的simulator中报错下述

![image](https://github.com/RoboMaster/IntelligentUAVChampionshipSimulator/assets/62043845/c39715ba-e34b-40f9-be6f-42e39da07f83)

**Comment by ShihaoLuo** [comment]
需要同步更新最新的 https://github.com/RoboMaster/IntelligentUAVChampionshipBase,  重新build以及source一下。 裡面的一些數據類型發生了一些改動。
