### ISSUE TITLE
airsim中的标定板尺寸大小能提供嘛？

### ISSUE THREAD

**Issue by YwyThunde** [RoboMaster/IntelligentUAVChampionshipSimulator#34]
前两天看到这个比赛，很感兴趣，想学习一下。但是已经过了报名时间。

**Comment by ShihaoLuo** [comment]
aprilgrid - tagCols:6 tagRows:6 tagSize:0.088 tagSpacing: 0.3
chessboard - Cols:11 Rows: 8 Width: 0.04 Height:  0.04
