### ISSUE TITLE
中央枢纽疑似存在空气墙，进不去

### ISSUE THREAD

**Issue by shaoPeng24** [RoboMaster/IntelligentUAVChampionshipSimulator#36]
![Screenshot from 2024-12-05 22-49-46](https://github.com/user-attachments/assets/05c6b2a8-9056-4bbf-86a8-ab18f925c497)
控制无人机往前飞，感觉像撞到东西了，进不去枢纽内部

**Comment by ShihaoLuo** [comment]
种子是多少

**Comment by shaoPeng24** [comment]
0 100 123 试了几个都过不去

**Comment by shaoPeng24** [comment]
> 种子是多少

0 100 123 试了几个都过不去

**Comment by ShihaoLuo** [comment]
确认是bug, 将尽快修复

**Comment by shaoPeng24** [comment]
> 确认是bug, 将尽快修复

![微信图片_20241207233824](https://github.com/user-attachments/assets/c77c1820-6174-4b4d-a214-60bfe7406cb0)
另外，无人机在中间这块区域会往下掉，难道中间属于通道外部吗？（0、123号种子，其他种子未测试）

**Comment by ShihaoLuo** [comment]
已修复
