### ISSUE TITLE
时间戳问题，不稳定，使用imu时间也会存在问题

### ISSUE THREAD

**Issue by Dong-melon** [RoboMaster/IntelligentUAVChampionshipSimulator#37]
模拟器的时间戳不同步，且这个差值不稳定，会逐渐变大，使用imu的时间戳作为全局时间会导致比例不对，难以实现定位，这个问题后续会解决吗？还是需要我们自己解决？
![微信图片_20241206142849](https://github.com/user-attachments/assets/a21901d1-1dd3-48f0-bc06-e1a6fa6f3984)

**Comment by ShihaoLuo** [comment]
这边看看

**Comment by ShihaoLuo** [comment]
已修复
