### ISSUE TITLE
枢纽到终点的入口处，无人机动力大幅度衰减

### ISSUE THREAD

**Issue by shaoPeng24** [RoboMaster/IntelligentUAVChampionshipSimulator#38]
![Screenshot from 2024-12-09 16-25-36](https://github.com/user-attachments/assets/43f223f6-c58c-4489-8504-163fd6f3dc3f)
![Screenshot from 2024-12-09 16-26-48](https://github.com/user-attachments/assets/b9b6494c-ad0a-43ad-a8fd-ce6954e01cdf)
在入口处，无人机动力失效，debug report 中的ctrl-in 为0.28，但ctrl-fl仅为0.07；此区域好像被定义成了通道或枢纽外部

**Comment by ShihaoLuo** [comment]
随机种子是多少

**Comment by shaoPeng24** [comment]
> 随机种子是多少

./run_simulator.sh  
后面没写种子

**Comment by DaydayXtt** [comment]
同样有这个问题

**Comment by ShihaoLuo** [comment]
已修复
