### ISSUE TITLE
模拟器的gps和（lidar，imu）时间戳不同步， 时间流速不同

### ISSUE THREAD

**Issue by fractal1z** [RoboMaster/IntelligentUAVChampionshipSimulator#41]
模拟器的gps和（lidar，imu）时间戳不同步， 时间流速不同，无法融合GPS数据
同https://github.com/RoboMaster/IntelligentUAVChampionshipSimulator/issues/37
请问是同类bug吗，这个问题后续会解决吗？
![2024-12-10 12-15-10 的屏幕截图](https://github.com/user-attachments/assets/385391b4-6a74-4a30-a73b-664df483dcc9)

**Comment by fractal1z** [comment]
此外，/airsim_node/drone_1/debug/pose_gt 与gps时间相同，能否将调试用的位姿真值也修改，方便调试？
![2024-12-10 12-38-38 的屏幕截图](https://github.com/user-attachments/assets/93624f9a-d1b3-4c53-977a-863db361fcf8)

**Comment by ShihaoLuo** [comment]
这个问题已修复，重新拉一下仓库。
