### ISSUE TITLE
IMU时间戳增量不均匀，会出现两个时刻的imu数据时间戳dt=0的情况

### ISSUE THREAD

**Issue by yudeli122** [RoboMaster/IntelligentUAVChampionshipSimulator#42]
<img width="819" alt="Screenshot 2024-12-10 125400" src="https://github.com/user-attachments/assets/15645bcc-cc80-4c46-b7b7-4a2193bd41c8">
如图，IMU时间戳与雷达时间戳对比，imu时间戳先快于雷达，之后出现imu时间戳停滞

**Comment by ShihaoLuo** [comment]
测试结果没有发现这个问题，尝试换一台好点的电脑再测测看。

![2024-12-10 17-54-13 的屏幕截图](https://github.com/user-attachments/assets/c00b709e-064b-4428-8ad4-447ea55a7611)
