### ISSUE TITLE
更新1209模拟器，IMU时间戳增量不一致，plotjuggler起初看是平行的，放大看....

### ISSUE THREAD

**Issue by FweiI** [RoboMaster/IntelligentUAVChampionshipSimulator#43]
運行定位模塊直接飄，打開話題看了眼imu和lidar的時間戳
![2024-12-10_21-45](https://github.com/user-attachments/assets/b3d100dc-90af-4914-ad87-f60ee37f3073)
請仔細看
![2024-12-10_21-45_1](https://github.com/user-attachments/assets/ad714049-b013-43ca-a8d0-9b772ab40156)
這是正常的嗎？

**Comment by wyk635** [comment]
我也有这个问题，无法进行预积分

**Comment by yudeli122** [comment]
已在高性能电脑上进行测试（i9-14900kf，rtx4090D，64G），在算力充足条件下录制数据，再次复现了此情况，IMU时间戳不稳定
<img width="695" alt="Screenshot 2024-12-11 131534" src="https://github.com/user-attachments/assets/5d937a30-6c0a-4a56-89a9-caae65930c98">
<img width="594" alt="Screenshot 2024-12-11 131559" src="https://github.com/user-attachments/assets/417acf7b-f745-4066-8077-9fa27b0d928b">

**Comment by ShihaoLuo** [comment]
已修复，请尝试一下修复版本。
