### ISSUE TITLE
关于比赛控制接口的疑问

### ISSUE THREAD

**Issue by Ding-Guo** [RoboMaster/IntelligentUAVChampionshipSimulator#45]
规则手册中写的无人机控制接口只有pwm，没有写速度控制接口，但是也没有地方说不让用速度控制接口
![image](https://github.com/user-attachments/assets/dfafcff7-30ed-4cc9-a453-34d2f3470cb6)
但是仿真器仓库里则写了有两个控制接口分别是速度控制接口和pwm控制接口。关键是速度控制接口的命名里面没有出现debug，而明确比赛时不会给但是调试时可以用的无人机状态真值数据命名是加了debug的。这很容易产生歧义。
![image](https://github.com/user-attachments/assets/1e8f415f-77b8-4eeb-afe6-6574f46461fe)
应该有规则明确是否只能使用pwm信号还是说速度信号控制和pwm信号控制都能用

**Comment by ShihaoLuo** [comment]
服务器仅会相应 PWM接口，这一点上规则是没有歧义的。
